### ISSUE TITLE
Show EDSM IDs for Ruins Interactive Map

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/CanonnApi#37]
For use with EDSM integration, need to have EDSM System and Body IDs given in the API response for the Ruins Map.

https://github.com/canonn-science/RuinsComboMap/commit/33a1ce7599a53387a0a8aee8b2501b27755d2dc5

**Comment by gingters** [comment]
Done in 8def339c5741514ab957341931c76d93dcd6ae16
